name: hypertrack
channels:
  - conda-forge
  - intel
#  - rapidsai
  - defaults
dependencies:
  - glib==2.76.4
  - tbb==2021.9.0
  - icc_rt==2023.1.0
  - python==3.10.11
  - cmake==3.26.4
  - gxx_linux-64==11.3.0
  - sysroot_linux-64==2.28
  - cudatoolkit==11.8.0
  - cudnn==8.8.0.121
  - faiss-cpu==1.7.4
#  - cugraph
#  - cugraph-pyg
